In [39]:
import pandas as pd

In [40]:
counts = pd.read_csv('../scraping/results.csv', index_col=0)

In [41]:
counts['student_count'].tolist()

[12, 4, 1, 4, 2, 0, 2, 3, 2, 2, 3, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [42]:
counts['professor_count'] = counts['professor_count'].clip(10)

In [43]:
counts['student_count'] = counts['student_count'] + 10

In [44]:
counts

,subject_ro,subject_eng,professor_count,student_count
0,matematica,mathematics,562,22
1,informatică,computer science,102,14
2,biologie,biology,186,11
3,chimie,chemistry,117,14
4,fizică,physics,82,12
5,geografie,geography,72,10
6,istorie,history,148,12
7,limba română,Romanian language,431,13
8,limba engleză,English language,532,12
9,limba franceză,French language,129,12
10,limba germană,German language,95,13
11,limba spaniolă,Spanish language,10,11
12,economie,economics,23,10
13,filosofie,philosophy,10,10
14,psihologie,psychology,29,11
15,sociologie,sociology,10,10
16,educație civică,civic education,10,10
17,științe politice,political science,10,10
18,arte vizuale,visual arts,10,10
19,muzică,music,25,10
20,educație fizică,physical education,10,10
21,tehnologia informației,information technology,15,10
22,religie,religion,10,10
23,management,management,10,10
24,contabilitate,accounting,23,10